version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.staging
    image: memoria-admin-client:staging
    container_name: cms-app-staging
    ports:
      - "81:80"
    restart: unless-stopped
