version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: memoria-admin-client:production
    container_name: cms-app-production
    ports:
      - "80:80"
    restart: unless-stopped
